language: generic
os: linux
dist: trusty

jobs:
  fast_finish: true
  allow_failures:
    - env: EMACS_VERSION=24.5
    - env: EMACS_VERSION=25.3
    - env: EMACS_VERSION=snapshot

env:
  - EMACS_VERSION=24.5
  - EMACS_VERSION=25.3
  - EMACS_VERSION=26.3
  - EMACS_VERSION=27.1
  - EMACS_VERSION=snapshot

before_install:
  # Configure $PATH: Executables are installed to $HOME/bin
  - export PATH="$HOME/bin:$PATH"
  # Download the makefile to emacs-travis.mk
  - wget 'https://raw.githubusercontent.com/rnikoopour/emacs-travis/bug/gnutls/emacs-travis.mk'
  # Install Emacs (according to $EMACS_VERSION) and Cask
  - make -f emacs-travis.mk install_emacs
  - make -f emacs-travis.mk install_cask

install:
  # Install your dependencies
  - cask install

script:
  # Run your tests
  - make test